export enum JobType {
  DISCOVER_EVENTS = 'DISCOVER_EVENTS',
  EVENT_DISCOVERY = 'EVENT_DISCOVERY',
  SCRAPE_SPONSORS = 'SCRAPE_SPONSORS',
  ENRICH_COMPANY = 'ENRICH_COMPANY',
  DISCOVER_PERSONAS = 'DISCOVER_PERSONAS',
}
