import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Conversation } from './conversation.entity';
import { OutreachStepTemplate } from './outreach-step-template.entity';

@Entity()
export class Message {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Conversation, (conversation) => conversation.messages)
  conversation: Conversation;

  @Column() // 'system', 'agent', 'user', 'contact'
  sender: string;

  @Column('text')
  content: string;

  // Link to the template if the message was generated by the system
  @ManyToOne(() => OutreachStepTemplate, { nullable: true })
  source_template: OutreachStepTemplate;

  @CreateDateColumn()
  created_at: Date;
}
