/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "event-analysis/functions/event_researcher.baml": "function ResearchEvents(location: string, year: int, topic: string) -> EventWithDetails[] {\n  client Claude3\n  \n  prompt #\"\n    You are an expert event researcher. Search for {{topic}} events in {{location}} for the year {{year}}.\n    \n    Find major conferences, summits, and expos related to {{topic}}.\n    \n    For each event found, extract:\n    - Event details (name, dates, venue, website)\n    - List of sponsors with their company information\n    - List of speakers with their professional details\n    \n    Return structured data following the schema.\n    Only include verified information. Use null for unknown fields.\n  \"#\n}",
  "event-analysis/models.baml": "class Event {\n  name string\n  year int\n  dates string?\n  venue string?\n  city string\n  country string?\n  industry string\n  attendeeCount int?\n  description string?\n  website string?\n  organizer string?\n  type string?\n}\n\nclass Company {\n  name string\n  website string?\n  industry string?\n  description string?\n  headquarters string?\n  founded int?\n  employeesRange string?\n}\n\nclass Sponsor {\n  company Company\n  sponsorshipTier string?\n}\n\nclass Person {\n  name string\n  title string?\n  company string?\n  email string?\n  phone string?\n  linkedinUrl string?\n  bio string?\n  location string?\n  expertise string[]?\n  sessionType string?\n  topic string?\n  role string?\n}\n\nclass EventWithDetails {\n  event Event\n  sponsors Sponsor[]\n  speakers Person[]\n}",
  "generators.baml": "generator target {\n    output_type \"typescript\"\n    output_dir \"../baml_client\"\n    version \"0.202.1\"\n    default_client_mode async\n}",
  "shared/clients.baml": "client<llm> GPT4 {\n  provider openai\n  options {\n    model \"gpt-4\"\n    temperature 0\n  }\n}\n\nclient<llm> Claude3 {\n  provider anthropic\n  options {\n    model \"claude-3-5-sonnet-20241022\"\n    max_tokens 4096\n    temperature 0\n  }\n}",
  "shared/config.baml": "retry_policy ExpBackoff {\n  max_retries 3\n  strategy {\n    type exponential_backoff\n    initial_delay_ms 1000\n    max_delay_ms 10000\n    multiplier 2\n  }\n}",
}
export const getBamlFiles = () => {
    return fileMap;
}